version: "3.*"

services:
  backend:
    command: ["npm", "run", "start:debug"]
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 7777:7777