version: "3.9"


volumes:
  data:

services:
  adminer:
    image: adminer
    depends_on:
      - database
    restart: always
    ports:
      - 8080:8080

  database:
    image: postgres:16.2-bullseye
    restart: always
    shm_size: 128mb
    volumes:
      - data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data/pgdata

  backend:
    command: ["npm", "run", "start:debug"]
    depends_on:
     - database
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 7777:7777